### PR TITLE
Fixes 

### LINKED ISSUE #49: Bug when using a query multiple times on the same screen
I've noticed some flickering, needs more investigation.

### PR DESCRIPTION
**Pull request by PetrKubes97**
Fixes #49,  #37 and  #34

### CODE REVIEW

**Review by KRTirtho — APPROVED** [review]
Awesome job 🚀 . Simple fix but a big riddle

**Comment by mauriciolcs** [comment]
any idea when these fixes will be released? i need the fix for issue #34

File: packages/fl_query/lib/src/core/query.dart [hunk 1]
```diff
@@ -184,6 +184,8 @@ class Query<DataType, ErrorType>
           if (error is ErrorType) _errorController.add(error);
```
Comment (mauriciolcs) [inline packages/fl_query/lib/src/core/query.dart:184]: maybe we'll have to throw the error here? otherwise this future will always be completed and we won't be able to handle the error.

```
try {
  await mutation.mutate()
} catch (e) {
  // treat error
}
```
